### ISSUE TITLE
Create UninstalledUrl for tracking uninstalls

### ISSUE THREAD

**Issue by glowka** [PrzypisPowszechny/pp#35]
Located at: `/site/extension-uninstalled/`
Triggering `ExtensionUninstalled` event from python backend (to make sure no GA blocks it).

GA requests reference docs: https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide
And _Hit Builder_ tool: https://ga-dev-tools.appspot.com/hit-builder/

### Details
**Problem:** GA code sets `_ga` and `_gid` cookie to track (anonymous) session, normally it is stored as cookie with domain set as the website URL, but in our case the script is run on site with the url set to _chrome://fsdfsd..._, so if we want extension not to break the session, we need to set the `_ga` and `_gid` cookies on `przypispowszechny.pl`.

**Solution Part1:**  Extension a while after initating GA script on our background page should ping backend endpoint.
 -  url: `/site/pings/init/`
 - with parameters `gid_cookie` and `ga_cookie` passed by `POST`, so body of the request looks like this `gid_cookie=GA1.3.262871750.1537573881&ga_cookie=GA1.3.2096600588.1532966673`
 - and the content type: `application/x-www-form-urlencoded`. 

The values come from the value of the cookies. The backend will send response that sets the cookies to the values from the request. This way, despite operating as a domainless extension we set cookies for the domain `przypispowszechny.pl` as it would happen for the normal website.

**Solution Part2:** When implementing `/site/extension-uninstalled/` endpoint will take the value from the cookies, strip `GA1.3.` prefix and use the values to construct query to GA. Query will be constructed following official resources: _Hit Duilder_ and GA docs linked above.

### Other info
Google analytics identifiers: `UA-123054125-1` (prod) or `UA-123054125-2` (dev) 

Map of all events: https://docs.google.com/spreadsheets/d/1QKMCeEtSoQ8UQt2VCmVjhWscd36nK5fv0RiJbOPzjmw/edit#gid=0

**Comment by glowka** [comment]
Solution details updated.

**Comment by kaglowka** [comment]
A complete and precise description of a problem and a solution, thanks! :+1:

**Comment by glowka** [comment]
Yeah, that's the problem, this steady URL is completely separate space from our domain (przypispowszechny.pl), so if you start GA script in that space and then visit our domain (which is the case for `/site/extension-uninstalled/` ) identities are also separate, because they are cookie-based and cookies are domain-based.

**Comment by kaglowka** [comment]
Oh, I see -- the problem is, as far as I understand, that we'd like to maintain the GA identity for client events within the extension as well as the event (currently the only one) that happens only on the server side.

That makes sense, since we'll most likely want to capture the connection between the user actions in the extensions and on the website (coming soon).
