### ISSUE TITLE
Improve privacy of PP GET annotation requests

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp#39]
**Ideas**
- use POST requests
- hash the requested URL

**Comment by glowka** [comment]
Hey. It's time we will soon take on this task, so I'd like to get down to some details.

I know idea of POSTing data as we discussed it that deeply, so it is crystal clear to me, but haven't heard of the concept of hashing (in that context). How is it meant to work and what are the privacy benefits?

> 
<sub>[View in Slack](https://przypispowszechny.slack.com/archives/CCDNT60UF/p1537699769000100)</sub>
