### ISSUE TITLE
Clean-up after initial integration with Demagog

### ISSUE THREAD

**Issue by glowka** [PrzypisPowszechny/pp#49]
Follow-up of: #47 

Improve logging: more logs of non-error situation, especially statistics like:
   - [x] "X sources read, took Y sec"
   - [x] "X new annotation created, took Y sec"
   - [x] change logging level from "error" to "warning" of situations when exception was raised by consumer, but handled by task

**Comment by kaglowka** [comment]
Please split it into more issues as we agreed at the meeting
