### ISSUE TITLE
Make `annotation` `quote` optional in POST

### ISSUE THREAD

**Issue by kaglowka** [PrzypisPowszechny/pp#52]
User-introduced annotations cannot be saved, since they only use `range` field.

**Comment by glowka** [comment]
Sure, that's the current state, but we decided that we want _all_ to have quote, so it's required now. Frontend need to change accordingly, but it shouldn't be a bid deal since you have information about quote "near" the range.

**Comment by glowka** [comment]
I would close this issue and open frontend one.

**Comment by kaglowka** [comment]
:+1:
