### ISSUE TITLE
Use CSRF token with POST/PUT/DELETE

### ISSUE THREAD

**Issue by glowka** [PrzypisPowszechny/pp#57]
API should require CSRF token from the client for the sake of the security.

**Comment by kaglowka** [comment]
I just checked it should be rather straightforward (Django by default saves `csrftoken` in the session cookie and as far as I remember checks it always for POST requests via the CSRF middleware)

**Comment by glowka** [comment]
Yep, this is Django feature, but we:
- do not use conventional Django class based views or function views, but Django-REST class base views, so we should enable CSRF token requirement manually
- afterwards we need to implement appending CSRF token on the frontend site, for every request

Both of them are not much of burden, but it's not typical out-of-the box working situation
