### ISSUE TITLE
Create endpoint for "request annotation" feature

### ISSUE THREAD

**Issue by glowka** [PrzypisPowszechny/pp#77]
Endpoint should save a record to database and send email about that.

Needed by https://github.com/PrzypisPowszechny/pp-client/issues/234.

**Comment by kaglowka** [comment]
Have we agreed that the request won't be saved in DB?

**Comment by glowka** [comment]
There were a couple of threads, and certainly output of one of them was that we do want to have it sent to our mailboxes. I am not sure if we eventually decided anything about DB, so I would make decision right now.

So situation is as follows:
 - it looks like it is not crucial for as to save requests to database, because it will be stored elsewhere anyway
 - we will neither use records stored in DB in viewing purposes for the same reason as above
- it still might make some sense to store them in DB in some way, to have this information within our grasp if want to develop this feature one day

So I would personally opt for storing this records in DB in very simple way, but at the same time I do not see it as a must-have.

**Comment by kaglowka** [comment]
Agreed, that's what I thought I have agreed on in the last meeting -- that it is a nice-to-have.
