### ISSUE TITLE
Fix the cause of DB rows flood

### ISSUE THREAD

**Issue by glowka** [PrzypisPowszechny/pp#89]
This is more "flood" than real flood as we have only 14k of them, but it is still surprising.

Investigate the cause and either upgrade DB plan (if no other way) or clean it and prevent future events.

**Comment by glowka** [comment]
We have 2k annotation, so will not get below that number, but in DB it is 14k, which is due to:
- 5400 rows – because of lazy signup every session = 3 rows: django_session + pp_user + lazysignup_lazyuser
- 7000 rows – annotation history

I see two options: we either dump the database by removing all annotations and all session and users, so that we have fresh DB with 2k records and it will take another us another quarter or two, or we start paying 9$ today. Dumping only annotation history and landing at 7k is not an option, because it will take us just couple of weeks to reach 10k again. 

Anyway, sooner or later we will start paying 9$.

@kaglowka  @KasiaSkowronska What's the decision for now, dump or paying?




ROWS 
django_session                       |       1752 |       
 pp_user                              |       1785 |         
 lazysignup_lazyuser                  |       1898 |          
 annotation_annotation                |       2152 |          
 annotation_historicalannotation      |       7053 |

**Comment by glowka** [comment]
@KasiaSkowronska please confirm that you are OK with deleting all data, including annotation, from current devdeploy1 database.

**Comment by KasiaSkowronska** [comment]
I have no objections

**Comment by glowka** [comment]
Done

**Comment by kaglowka** [comment]
Thx!
