### ISSUE TITLE
Move przypispowszechny.pl to other provider or switch to subdomain

### ISSUE THREAD

**Issue by glowka** [PrzypisPowszechny/pp#94]
There is no way to set przypispowszechny.pl as CNAME at home.pl, they changed the system and haven't updated docs.

Tentatively, these are possible solutions: move the domain to other provider which supports ANAME or start using subdomain, eg. app.przypispowszechny.pl. With the latter, additionally some redirections on root domain would be needed.

**Comment by kaglowka** [comment]
Thanks for the check.

> With the latter, additionally some redirections on root domain would be needed.
You mean 301 redirect, right?

I believe a subdomain will do for now (with redirect from the root `przypispowszechny.pl` or not).
At this stage our domain is hardly ever used by the users anyway (mostly API requests).

In the long run we should probably change the provider anyway so I guess we can just do it when the time comes -- I've heard Home.pl prices increase nastily for long-term users.

**Comment by kaglowka** [comment]
I believe this is done? :)

**Comment by kaglowka** [comment]
I do believe this is done :)

**Comment by glowka** [comment]
:D
